[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gong_de_increase = "9jpqDtrTj4GyNLVDjydbJVW1pWkZypHwpqDyLt2Ragt9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./sol/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
